tasks:
  # - STS-B
  # - CoLA
  # - SST-2
  # - QQP
  - MNLI
  - QNLI
  - RTE
metadata_file: "/content/cramBERT/glue_metadata.yaml"
tokenizer_path: "/content/cramBERT/webtext/tokenizer.json"
num_epochs: 5
batch_size: 16
lr: 4.0e-5
weight_decay: 0.01
dropout: 0.1
checkpoint_path: "/content/drive/MyDrive/cramBERT/model_checkpoints/32000.pt"