tasks:
  - CoLA
  - SST-2
  - QQP
  - STS-B
  - MNLI
  - QNLI
  - RTE
metadata_file: "/content/cramBERT/glue_metadata.yaml"
num_epochs: 5
batch_size: 32
lr: 1.0e-5
weight_decay: 0.01
dropout: 0.1
checkpoint_path: "/content/drive/MyDrive/cramBERT/model_checkpoints/32000.pt"